version: 2.1
executors:
  flask-executor:
    docker:
      - image: python:3.12.11-slim
jobs:
  backend_test:
    executor: flask-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - ad-astra-${{ .Environment.CIRCLE_BRANCH }}-v3-{{ checksum "requirements.txt" }}
      - run:
          name: Install Flask App Rquirements
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Show pytest executable dir
          command: pip show pytest playwright
      - run:
          name: Install Playwright Dependencies
          command: |
            playwright install
            playwright install-deps
      - run:
          name: Run Backend Tests
          command: pytest --maxfail=1 --junitxml=junit-reports/backend_test_report.xml tests/test_backend.py
      - save_cache:
          key: ad-astra-${{ .Environment.CIRCLE_BRANCH }}-v3-{{ checksum "requirements.txt" }}
          paths:
            - /usr/local/lib/python3.12/site-packages
      - store_artifacts:
          path: junit-reports
          destination: junit-reports
      - store_test_results:
          path: junit-reports


  frontend_test:
    executor: flask-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - ad-astra-${{ .Environment.CIRCLE_BRANCH }}-v3-{{ checksum "requirements.txt" }}
      - run:
          name: Run Frontend tTsts
          command: pytest --maxfail=1 ---junitxml=junit-reports/backend_test_report.xml tests/test_frontend.py
      - store_artifacts:
          path: junit-reports
          destination: junit-reports
      - store_test_results:
          path: junit-reports  

workflows:
  version: 2
  test:
    jobs:
      - backend_test
      - frontend_test:
          requires:
            - backend_test