version: 2.1
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: Install Flask App Rquirements
          command: pip3 install -r requirements.txt
      - run:
          name: Install Chromium for store_test
          command: playwright install
      - run:
          name: Run WebApp Autotest
          command: pytest -v