version: 2.1
executors:
  flask-backend-executor:
    docker:
      - image: python:3.12.11-alpine3.22
  flask-frontend:
    docker:
      - image: mcr.microsoft.com/playwright/python:v1.55.0-noble
jobs:
  backend_test:
    executor: flask-backend-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - ad-astra-${{ .Environment.CIRCLE_BRANCH }}-${{ .Environment.PIP_CACHE_VERSION }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Flask App Rquirements
          command: pip3 install -r requirements.txt
      - run:
          name: Run Backend Tests
          command: pytest --maxfail=1 --junitxml=report-$(echo CIRCLE_JOB)-$(echo CIRCLE_WORKFLOW_JOB_ID) tests/test_backend.py
      - save_cache:
          key: ad-astra-${{ .Environment.CIRCLE_BRANCH }}-${{ .Environment.PIP_CACHE_VERSION }}-{{ checksum "requirements.txt" }}
          paths:
            - /usr/local/lib/python3.12/dist-packages

  frontend_test:
    executor: flask-frontend
    steps:
      - checkout
      - restore_cache:
          keys:
            - ad-astra-${{ .Environment.CIRCLE_BRANCH }}-${{ .Environment.PIP_CACHE_VERSION }}-{{ checksum "requirements.txt" }}
      - run:
          name: Run Frontend tTsts
          command: pytest --maxfail=1 --junitxml=report-$(CIRCLE_JOB)-$(CIRCLE_WORKFLOW_JOB_ID) tests/test_frontend.py

workflows:
  version: 2
  test:
    jobs:
      - backend_test
      - frontend_test
        requires:
          - backend_test