version: 2.1
executors:
  flask-backend-executor:
    docker:
      - image: python:3.12.11-slim-bookworm
  flask-frontend:
    docker:
      - image: mcr.microsoft.com/playwright/python:v1.55.0-noble
jobs:
  backend_test:
    executor: flask-backend-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - ad-astra-${{ .Environment.CIRCLE_BRANCH }}-v2.1-{{ checksum "requirements.txt" }}
      - run:
          name: Install Flask App Rquirements
          command: |
            pip install --upgrade pip
            pip install --target /usr/local/lib/python3.12/dist-packages -r requirements.txt
      - run:
          name: Show PIP packages
          command: pip show playwright
      - run:
          name: List Python Dist Dir
          command: ls -la /usr/local/lib/python3.12/dist-packages
      - run:
          name: Add Pip Distro Dir to Path
          command: export PATH=/usr/local/lib/python3.12/dist-packages:$PATH
      - run:
          name: check PATH
          command: echo $PATH
      - run:
          name: Run Backend Tests
          command: pytest --maxfail=1 --junitxml=junit-reports/backend_test_report.xml tests/test_backend.py
      - save_cache:
          key: ad-astra-${{ .Environment.CIRCLE_BRANCH }}-v2.1-{{ checksum "requirements.txt" }}
          paths:
            - /usr/local/lib/python3.12/dist-packages
      - store_artifacts:
          path: junit-reports
          destination: junit-reports
      - store_test_results:
          path: junit-reports


  frontend_test:
    executor: flask-frontend
    steps:
      - checkout
      - restore_cache:
          keys:
            - ad-astra-${{ .Environment.CIRCLE_BRANCH }}-v2.1-{{ checksum "requirements.txt" }}
      - run:
          name: Run Frontend tTsts
          command: pytest --maxfail=1 ---junitxml=junit-reports/backend_test_report.xml tests/test_frontend.py
      - store_artifacts:
          path: junit-reports
          destination: junit-reports
      - store_test_results:
          path: junit-reports  

workflows:
  version: 2
  test:
    jobs:
      - backend_test
      - frontend_test:
          requires:
            - backend_test