version: 2.1
executors:
  flask-executor:
    docker:
      - image: playwright/firefox
jobs:
  backend_test:
    executor: flask-executor
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - ad-astra-${CIRCLE_BRANCH}-{{checksum requirements.txt}}
      - run:
          name: Install Flask App Rquirements
          command: pip3 install -r requirements.txt
      - run:
          name: Run Backend tests
          command: pytest --maxfail=1 --junitxml=report-${CIRCLE_JOB}-${CIRCLE_WORKFLOW_JOB_ID}
      # - save_cache:
      - run:
          name: Find PIP packeges location
          command: find / -name flask*
