version: 2.1
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: Install Flask App Rquirements
          command: pip3 install -r requirements.txt
      - run:
          name: Flask Auto Tests
          command: flask run &