version: 2.1
executors:
  flask-backend-executor:
    docker:
      - image: python:3.12.11-slim-bookworm
  flask-frontend:
    docker:
      - image: mcr.microsoft.com/playwright/python:v1.55.0-noble
jobs:
  backend_test:
    executor: flask-backend-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - ad-astra-${{ .Environment.CIRCLE_BRANCH }}-${{ .Environment.PIP_CACHE_VERSION }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Flask App Rquirements
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Show PIP packages
          command: pip show playwright
      - run:
          name: List Python Dist Dir
          command: ls -la /usr/local/lib/python3.12/dist-packages
      - run:
          name: Run Backend Tests
          command: pytest --maxfail=1 --junitxml=report-${{ .Environment.CIRCLE_BRANCH }}-${{ .Environment.CIRCLE_BRANCH }} tests/test_backend.py
      - save_cache:
          key: ad-astra-${{ .Environment.CIRCLE_BRANCH }}-${{ .Environment.PIP_CACHE_VERSION }}-{{ checksum "requirements.txt" }}
          paths:
            - /usr/local/lib/python3.12/dist-packages

  frontend_test:
    executor: flask-frontend
    steps:
      - checkout
      - restore_cache:
          keys:
            - ad-astra-${{ .Environment.CIRCLE_BRANCH }}-${{ .Environment.PIP_CACHE_VERSION }}-{{ checksum "requirements.txt" }}
      - run:
          name: Run Frontend tTsts
          command: pytest --maxfail=1 --junitxml=report-${{ .Environment.CIRCLE_BRANCH }}-${{ .Environment.CIRCLE_BRANCH }} tests/test_frontend.py

workflows:
  version: 2
  test:
    jobs:
      - backend_test
      - frontend_test:
          requires:
            - backend_test